### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by thejoester** [7H3LaughingMan/wayfinder#1]
I cannot tell what this module adds to the game or how to use it. No documentation or anything is provided and I see no difference when moving my actors.

**Comment by uniwars** [comment]
same ^^

**Comment by 7H3LaughingMan** [comment]
https://github.com/7H3LaughingMan/wayfinder?tab=readme-ov-file#troubleshooting

**Comment by thejoester** [comment]
I see that you added this in the README, thank you!
