### ISSUE TITLE
Proposal for french translation

### ISSUE THREAD

**Issue by Jemipet** [7H3LaughingMan/wayfinder#13]
Hello
I'm not an English speaker and I'm not a coder.
My proposal may therefore not comply with the Foundry or Github standard.
I hope that this translation can be offered to French-speakers.
Yours sincerely.

# Wayfinder

**Restriction d'exploration du brouillard**

Lorsqu'elle est activée, la recherche de chemin sera limitée uniquement aux parties de la carte qui ont déjà été explorées.

**Historique des mouvements**

Lorsqu'elle est activée, cela suivra le mouvement d'un jeton pendant le combat et le réinitialisera au début du tour du jeton.

**Terrain difficile**

Lorsqu'elle est activée, le coût supplémentaire de déplacement à travers un terrain difficile sera affiché.

**Icônes d'action**

Lorsqu'elle est activée, le nombre d'actions nécessaires pour déplacer un jeton sera affiché.

**Comment by 7H3LaughingMan** [comment]
If you would like to submit a translation, please use GitLocalize.

https://gitlocalize.com/repo/9859

**Comment by Jemipet** [comment]
Merci, mais comme je n'arrive même pas à m'inscrire :).
Impossible pour moi de faire une tentative de traduction.
Tout ceci est bien au-delà de mes compétences techniques.
Je vais essayer de trouver quelqu'un dans la communauté Francophone que cela pourrait intéresser.
Bon WE et joyeuses fêtes.
