### ISSUE TITLE
Hexagon problems

### ISSUE THREAD

**Issue by SilverLous** [7H3LaughingMan/wayfinder#3]
On Squares it works fine. On Hex it seems to need a completely free space to be able to navigate to

![image](https://github.com/user-attachments/assets/1268d172-84c7-4c1e-966b-86a19da8ddc7)

![image](https://github.com/user-attachments/assets/26a4a55e-68ec-455a-bbf9-195544dcfd8a)

![image](https://github.com/user-attachments/assets/c4e6f58e-ebd4-4953-9fb5-189426d0ee8d)

**Comment by 7H3LaughingMan** [comment]
Fixed in v6.5.3

**Comment by SilverLous** [comment]
Oh thanks for the quick fix, this is great!

**Comment by 7H3LaughingMan** [comment]
@SilverLous Quick question, how are you able to drag the tokens around while keeping the walls visible.

**Comment by SilverLous** [comment]
it's from https://github.com/ironmonk88/monks-wall-enhancement
Toggle Walls display
