### ISSUE TITLE
[Feature Request] Option to disable wayfinding for invisible walls

### ISSUE THREAD

**Issue by Aziareel** [7H3LaughingMan/wayfinder#7]
In Foundry you can place invisible walls.
So maybe an option to disable wayfinding for these walls. After all you would not be able to see them.

However this leads to interactions where spells like See the Unseen might let you see invisible walls and the likes.

**Comment by 7H3LaughingMan** [comment]
The problem with this is that Foundry itself does not care what kind of wall is preventing token movement. This means that if a player tries to take a path that does go through an invisible wall they will get an error that the path is blocked and their token will never move.
